name: playground
description: 'A Flutter project to play around with different tools and technologies'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
